// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"

// tests for exercise 1
TEST_CASE("Test1 ", "[T1]")
{
	int n1, n2;
	int p1, p2;
	getTwoValues(n1, n2);
	p1 = getNextPrime(n1);
	p2 = getPrevPrime(n2);
	REQUIRE(p1 == 211);
	REQUIRE(p2 == 241);

	n1 = 200;
	n2 = 250;
	p1 = getNextPrime(n1);
	p2 = getPrevPrime(n2);

	REQUIRE(p1 == 211);
	REQUIRE(p2 == 241);
}
TEST_CASE("Test2 ", "[T2]")
{
	int n1, n2;
	int p1, p2;
	// getTwoValues(n1, n2);
	n1 = 1350;
	n2 = 1360;
	p1 = getNextPrime(n1);
	p2 = getPrevPrime(n2);

	REQUIRE(p1 == 1361);
	REQUIRE(p2 == 1327);
}


TEST_CASE("Test3 ", "[T3]")
{
	int n1, n2;
	getTwoValues(n1, n2);
	REQUIRE(n1 == 10);
	REQUIRE(n2 == 20);
	int p1 = getNextPrime(n1);
	int p2 = getPrevPrime(n2);

	REQUIRE(p1 == 11);
	REQUIRE(p2 == 19);
}

TEST_CASE("Test4 ", "[T4]")
{
	int n1, n2;
	n1 = 10010;
	n2 = 10050;
	int p1 = getNextPrime(n1);
	int p2 = getPrevPrime(n2);

	REQUIRE(p1 == 10037);
	REQUIRE(p2 == 10039);
}